@startuml
title Diagramme d'activité : Gerer le panier

|Client|
start
:Accéder au panier;

if (Panier vide ?) then (oui)

    if (Connecté ?) then (oui)
        |Client|
        if (Ajouter un article ?) then (oui)
            :Sélectionner article;
            |Systeme|
            :Ajouter article au panier;
            stop
        else (non)
            |Client|
            stop
        endif

    else (non)
        |Client|
        :Afficher message "Vous devez vous connectez pour pouvoir passer commande";
        stop
    endif

else (non)

    repeat

        if (Modifier panier ?) then (oui)

            |Client|
            if (Ajouter un article ?) then (oui)

                :Sélectionner article;
                |Systeme|
                :Ajouter article au panier;
                stop

            else (non)

                |Client|
                if (Modifier article existant ?) then (oui)
                    :Sélectionner article;

                    if (Supprimer ?) then (Non)
                        |Client|
                        :Sélectionner spécifications;
                        |Systeme|
                        :Modifier article;
                        stop
                    else (Oui)
                        |Systeme|
                        :Supprimer l'article;
                        stop
                        
                    endif
                
                else (non)
                    |Systeme|
                    ' Aucune modification
                endif

            endif
        
        else (non)
            
            break
        endif
    
    repeat while (Modifier encore ?)

endif

stop
@enduml
