@startuml
title Diagramme d'activité : Consulter le catalogue

|Client|
start
:Accéder au panier;

if (Panier vide ?) then (oui)

    if (Connecté ?) then (oui)
        |Client|
        if (Ajouter un article ?) then (oui)
            :Sélectionner article;
            |Systeme|
            :Ajouter article;
        else (non)
            |Client|
            stop
        endif

    else (non)
        |Systeme|
        :Se connecter;
    endif

else (non)

    repeat

        if (Modifier panier ?) then (oui)

            |Client|
            if (Ajouter un article ?) then (oui)

                :Sélectionner article;
                |Systeme|
                :Ajouter article au panier;

            else (non)

                |Client|
                if (Modifier article existant ?) then (oui)
                    :Sélectionner article;

                    if (Supprimer ?) then (oui)
                        |Systeme|
                        :Supprimer l'article;
                    else (non)
                        |Client|
                        :Sélectionner spécifications;
                        |Systeme|
                        :Modifier article;
                    endif

                else (non)
                    ' Aucune modification
                endif

            endif

        else (non)
            break
        endif

    repeat while (Modifier encore ?)

endif

stop
@enduml
